# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\OOP\travelcompany\gui\AboutOrderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutOrderWindow(object):
    def setupUi(self, AboutOrderWindow):
        AboutOrderWindow.setObjectName("AboutOrderWindow")
        AboutOrderWindow.resize(553, 497)
        AboutOrderWindow.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(248, 248, 248)")
        self.centralwidget = QtWidgets.QWidget(AboutOrderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setHorizontalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelCountry = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCountry.sizePolicy().hasHeightForWidth())
        self.labelCountry.setSizePolicy(sizePolicy)
        self.labelCountry.setText("")
        self.labelCountry.setObjectName("labelCountry")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelCountry)
        self.labelPrice = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPrice.sizePolicy().hasHeightForWidth())
        self.labelPrice.setSizePolicy(sizePolicy)
        self.labelPrice.setText("")
        self.labelPrice.setObjectName("labelPrice")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelPrice)
        self.labelDeparture = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDeparture.sizePolicy().hasHeightForWidth())
        self.labelDeparture.setSizePolicy(sizePolicy)
        self.labelDeparture.setText("")
        self.labelDeparture.setObjectName("labelDeparture")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelDeparture)
        self.labelStart = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStart.sizePolicy().hasHeightForWidth())
        self.labelStart.setSizePolicy(sizePolicy)
        self.labelStart.setText("")
        self.labelStart.setObjectName("labelStart")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelStart)
        self.labelEnd = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEnd.sizePolicy().hasHeightForWidth())
        self.labelEnd.setSizePolicy(sizePolicy)
        self.labelEnd.setText("")
        self.labelEnd.setObjectName("labelEnd")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelEnd)
        self.labelVisa = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVisa.sizePolicy().hasHeightForWidth())
        self.labelVisa.setSizePolicy(sizePolicy)
        self.labelVisa.setText("")
        self.labelVisa.setObjectName("labelVisa")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelVisa)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.labelName = QtWidgets.QLabel(self.groupBox)
        self.labelName.setText("")
        self.labelName.setObjectName("labelName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelName)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.labelFIO = QtWidgets.QLabel(self.groupBox_2)
        self.labelFIO.setText("")
        self.labelFIO.setObjectName("labelFIO")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelFIO)
        self.labelBirth = QtWidgets.QLabel(self.groupBox_2)
        self.labelBirth.setText("")
        self.labelBirth.setObjectName("labelBirth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelBirth)
        self.labelPhone = QtWidgets.QLabel(self.groupBox_2)
        self.labelPhone.setText("")
        self.labelPhone.setObjectName("labelPhone")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelPhone)
        self.labelEmail = QtWidgets.QLabel(self.groupBox_2)
        self.labelEmail.setText("")
        self.labelEmail.setObjectName("labelEmail")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelEmail)
        self.labelPassport = QtWidgets.QLabel(self.groupBox_2)
        self.labelPassport.setText("")
        self.labelPassport.setObjectName("labelPassport")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelPassport)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setStyleSheet("color: rgba(255, 255, 255,0);")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.labelOrderDate = QtWidgets.QLabel(self.groupBox_2)
        self.labelOrderDate.setText("")
        self.labelOrderDate.setObjectName("labelOrderDate")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelOrderDate)
        self.verticalLayout.addWidget(self.groupBox_2)
        AboutOrderWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AboutOrderWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutOrderWindow)

    def retranslateUi(self, AboutOrderWindow):
        _translate = QtCore.QCoreApplication.translate
        AboutOrderWindow.setWindowTitle(_translate("AboutOrderWindow", "Информация о заказе"))
        self.groupBox.setTitle(_translate("AboutOrderWindow", "Информация о туре"))
        self.label_6.setText(_translate("AboutOrderWindow", "Страна:"))
        self.label_7.setText(_translate("AboutOrderWindow", "Цена:"))
        self.label_8.setText(_translate("AboutOrderWindow", "Место отправления:"))
        self.label_9.setText(_translate("AboutOrderWindow", "Дата выезда:"))
        self.label_10.setText(_translate("AboutOrderWindow", "Дата приезда:"))
        self.label_11.setText(_translate("AboutOrderWindow", "Виза:"))
        self.label_12.setText(_translate("AboutOrderWindow", "Название:"))
        self.groupBox_2.setTitle(_translate("AboutOrderWindow", "Информация о заказчике"))
        self.label.setText(_translate("AboutOrderWindow", "ФИО:"))
        self.label_3.setText(_translate("AboutOrderWindow", "Дата рождения:"))
        self.label_2.setText(_translate("AboutOrderWindow", "Телефон:"))
        self.label_4.setText(_translate("AboutOrderWindow", "Email:"))
        self.label_5.setText(_translate("AboutOrderWindow", "Номер паспорта:"))
        self.label_13.setText(_translate("AboutOrderWindow", "Место отправления:"))
        self.label_14.setText(_translate("AboutOrderWindow", "Дата заказа:"))

