# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\OOP\travelcompany\gui\AddTourWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddTourWindow(object):
    def setupUi(self, AddTourWindow):
        AddTourWindow.setObjectName("AddTourWindow")
        AddTourWindow.resize(467, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddTourWindow.sizePolicy().hasHeightForWidth())
        AddTourWindow.setSizePolicy(sizePolicy)
        AddTourWindow.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(248, 248, 248)")
        self.centralwidget = QtWidgets.QWidget(AddTourWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.dateStart = QtWidgets.QDateEdit(self.centralwidget)
        self.dateStart.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateStart.setObjectName("dateStart")
        self.gridLayout.addWidget(self.dateStart, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineCountry = QtWidgets.QLineEdit(self.centralwidget)
        self.lineCountry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineCountry.setObjectName("lineCountry")
        self.gridLayout.addWidget(self.lineCountry, 1, 1, 1, 1)
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineName.setObjectName("lineName")
        self.gridLayout.addWidget(self.lineName, 0, 1, 1, 1)
        self.lineDeparture = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDeparture.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineDeparture.setObjectName("lineDeparture")
        self.gridLayout.addWidget(self.lineDeparture, 2, 1, 1, 1)
        self.dateEnd = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEnd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEnd.setObjectName("dateEnd")
        self.gridLayout.addWidget(self.dateEnd, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.doubleSpinPrice = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinPrice.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinPrice.setMaximum(99999.99)
        self.doubleSpinPrice.setObjectName("doubleSpinPrice")
        self.gridLayout.addWidget(self.doubleSpinPrice, 6, 1, 1, 1)
        self.buttonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAdd.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.buttonAdd.setObjectName("buttonAdd")
        self.gridLayout.addWidget(self.buttonAdd, 10, 0, 1, 2)
        self.checkBoxVisa = QtWidgets.QCheckBox(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.checkBoxVisa.setPalette(palette)
        self.checkBoxVisa.setStyleSheet("")
        self.checkBoxVisa.setObjectName("checkBoxVisa")
        self.gridLayout.addWidget(self.checkBoxVisa, 7, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(7, 0, 7, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textDescription = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textDescription.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textDescription.setObjectName("textDescription")
        self.verticalLayout.addWidget(self.textDescription)
        self.gridLayout.addLayout(self.verticalLayout, 8, 0, 1, 2)
        AddTourWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddTourWindow)
        QtCore.QMetaObject.connectSlotsByName(AddTourWindow)
        AddTourWindow.setTabOrder(self.lineName, self.lineCountry)
        AddTourWindow.setTabOrder(self.lineCountry, self.lineDeparture)
        AddTourWindow.setTabOrder(self.lineDeparture, self.dateStart)
        AddTourWindow.setTabOrder(self.dateStart, self.dateEnd)
        AddTourWindow.setTabOrder(self.dateEnd, self.doubleSpinPrice)
        AddTourWindow.setTabOrder(self.doubleSpinPrice, self.checkBoxVisa)
        AddTourWindow.setTabOrder(self.checkBoxVisa, self.buttonAdd)

    def retranslateUi(self, AddTourWindow):
        _translate = QtCore.QCoreApplication.translate
        AddTourWindow.setWindowTitle(_translate("AddTourWindow", "Новый тур"))
        self.label_4.setText(_translate("AddTourWindow", "Дата приезда:"))
        self.label_7.setText(_translate("AddTourWindow", "Выезд из:"))
        self.label_3.setText(_translate("AddTourWindow", "Дата выезда:"))
        self.label.setText(_translate("AddTourWindow", "Название:"))
        self.label_2.setText(_translate("AddTourWindow", "Страна:"))
        self.label_8.setText(_translate("AddTourWindow", "Цена, USD:"))
        self.buttonAdd.setText(_translate("AddTourWindow", "Добавить"))
        self.checkBoxVisa.setText(_translate("AddTourWindow", "Виза"))

