# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\travelcompany\gui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 788)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(248, 248, 248);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menu.setFont(font)
        self.menu.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_2.setContentsMargins(-1, 25, -1, 25)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonTours = QtWidgets.QToolButton(self.menu)
        self.buttonTours.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTours.sizePolicy().hasHeightForWidth())
        self.buttonTours.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonTours.setFont(font)
        self.buttonTours.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonTours.setAutoFillBackground(False)
        self.buttonTours.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.buttonTours.setIconSize(QtCore.QSize(120, 120))
        self.buttonTours.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.buttonTours.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.buttonTours.setAutoRaise(False)
        self.buttonTours.setArrowType(QtCore.Qt.NoArrow)
        self.buttonTours.setObjectName("buttonTours")
        self.verticalLayout_2.addWidget(self.buttonTours)
        self.buttonOrders = QtWidgets.QToolButton(self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOrders.sizePolicy().hasHeightForWidth())
        self.buttonOrders.setSizePolicy(sizePolicy)
        self.buttonOrders.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.buttonOrders.setIconSize(QtCore.QSize(120, 120))
        self.buttonOrders.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.buttonOrders.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.buttonOrders.setObjectName("buttonOrders")
        self.verticalLayout_2.addWidget(self.buttonOrders)
        self.buttonCustomers = QtWidgets.QToolButton(self.menu)
        self.buttonCustomers.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCustomers.sizePolicy().hasHeightForWidth())
        self.buttonCustomers.setSizePolicy(sizePolicy)
        self.buttonCustomers.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.buttonCustomers.setIconSize(QtCore.QSize(120, 120))
        self.buttonCustomers.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.buttonCustomers.setObjectName("buttonCustomers")
        self.verticalLayout_2.addWidget(self.buttonCustomers)
        self.buttonToursArchive = QtWidgets.QToolButton(self.menu)
        self.buttonToursArchive.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonToursArchive.sizePolicy().hasHeightForWidth())
        self.buttonToursArchive.setSizePolicy(sizePolicy)
        self.buttonToursArchive.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonToursArchive.setAutoFillBackground(False)
        self.buttonToursArchive.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.buttonToursArchive.setIconSize(QtCore.QSize(120, 120))
        self.buttonToursArchive.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.buttonToursArchive.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.buttonToursArchive.setAutoRaise(False)
        self.buttonToursArchive.setArrowType(QtCore.Qt.NoArrow)
        self.buttonToursArchive.setObjectName("buttonToursArchive")
        self.verticalLayout_2.addWidget(self.buttonToursArchive)
        self.buttonAbout = QtWidgets.QToolButton(self.menu)
        self.buttonAbout.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAbout.sizePolicy().hasHeightForWidth())
        self.buttonAbout.setSizePolicy(sizePolicy)
        self.buttonAbout.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.buttonAbout.setIconSize(QtCore.QSize(120, 120))
        self.buttonAbout.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.buttonAbout.setObjectName("buttonAbout")
        self.verticalLayout_2.addWidget(self.buttonAbout)
        self.horizontalLayout.addWidget(self.menu)
        self.vLine = QtWidgets.QFrame(self.centralwidget)
        self.vLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.vLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vLine.setObjectName("vLine")
        self.horizontalLayout.addWidget(self.vLine)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.stackedWidget.setPalette(palette)
        self.stackedWidget.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageTours = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageTours.sizePolicy().hasHeightForWidth())
        self.pageTours.setSizePolicy(sizePolicy)
        self.pageTours.setObjectName("pageTours")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageTours)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(63, 63, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.pageTours)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 63))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.buttonAddTour = QtWidgets.QPushButton(self.pageTours)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddTour.sizePolicy().hasHeightForWidth())
        self.buttonAddTour.setSizePolicy(sizePolicy)
        self.buttonAddTour.setMaximumSize(QtCore.QSize(16777215, 63))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonAddTour.setFont(font)
        self.buttonAddTour.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.buttonAddTour.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAddTour.setIcon(icon)
        self.buttonAddTour.setIconSize(QtCore.QSize(50, 50))
        self.buttonAddTour.setAutoDefault(False)
        self.buttonAddTour.setObjectName("buttonAddTour")
        self.horizontalLayout_2.addWidget(self.buttonAddTour)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 20)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollTourList = QtWidgets.QScrollArea(self.pageTours)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollTourList.sizePolicy().hasHeightForWidth())
        self.scrollTourList.setSizePolicy(sizePolicy)
        self.scrollTourList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollTourList.setWidgetResizable(True)
        self.scrollTourList.setObjectName("scrollTourList")
        self.scrollTourListContents = QtWidgets.QWidget()
        self.scrollTourListContents.setGeometry(QtCore.QRect(0, 0, 923, 672))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollTourListContents.sizePolicy().hasHeightForWidth())
        self.scrollTourListContents.setSizePolicy(sizePolicy)
        self.scrollTourListContents.setObjectName("scrollTourListContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollTourListContents)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.scrollTourListContents)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.scrollTourList.setWidget(self.scrollTourListContents)
        self.verticalLayout_3.addWidget(self.scrollTourList)
        self.stackedWidget.addWidget(self.pageTours)
        self.pageOrders = QtWidgets.QWidget()
        self.pageOrders.setObjectName("pageOrders")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageOrders)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.pageOrders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 63))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 63))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3.setStretch(0, 20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.scrollOrderList = QtWidgets.QScrollArea(self.pageOrders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollOrderList.sizePolicy().hasHeightForWidth())
        self.scrollOrderList.setSizePolicy(sizePolicy)
        self.scrollOrderList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollOrderList.setWidgetResizable(True)
        self.scrollOrderList.setObjectName("scrollOrderList")
        self.scrollOrderListContents = QtWidgets.QWidget()
        self.scrollOrderListContents.setGeometry(QtCore.QRect(0, 0, 98, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollOrderListContents.sizePolicy().hasHeightForWidth())
        self.scrollOrderListContents.setSizePolicy(sizePolicy)
        self.scrollOrderListContents.setObjectName("scrollOrderListContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollOrderListContents)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.scrollOrderListContents)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.scrollOrderList.setWidget(self.scrollOrderListContents)
        self.verticalLayout_5.addWidget(self.scrollOrderList)
        self.stackedWidget.addWidget(self.pageOrders)
        self.pageCustomers = QtWidgets.QWidget()
        self.pageCustomers.setObjectName("pageCustomers")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageCustomers)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.pageCustomers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 63))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 63))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_5.setStretch(0, 20)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.scrollCustomerList = QtWidgets.QScrollArea(self.pageCustomers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollCustomerList.sizePolicy().hasHeightForWidth())
        self.scrollCustomerList.setSizePolicy(sizePolicy)
        self.scrollCustomerList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollCustomerList.setWidgetResizable(True)
        self.scrollCustomerList.setObjectName("scrollCustomerList")
        self.scrollCustomerListContents = QtWidgets.QWidget()
        self.scrollCustomerListContents.setGeometry(QtCore.QRect(0, 0, 923, 672))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollCustomerListContents.sizePolicy().hasHeightForWidth())
        self.scrollCustomerListContents.setSizePolicy(sizePolicy)
        self.scrollCustomerListContents.setObjectName("scrollCustomerListContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollCustomerListContents)
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.scrollCustomerListContents)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.scrollCustomerList.setWidget(self.scrollCustomerListContents)
        self.verticalLayout_11.addWidget(self.scrollCustomerList)
        self.stackedWidget.addWidget(self.pageCustomers)
        self.pageToursArchive = QtWidgets.QWidget()
        self.pageToursArchive.setObjectName("pageToursArchive")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageToursArchive)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.pageToursArchive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 63))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 63))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_4.setStretch(0, 20)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.scrollArchiveTourList = QtWidgets.QScrollArea(self.pageToursArchive)
        self.scrollArchiveTourList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArchiveTourList.setWidgetResizable(True)
        self.scrollArchiveTourList.setObjectName("scrollArchiveTourList")
        self.scrollArchiveTourListContents = QtWidgets.QWidget()
        self.scrollArchiveTourListContents.setGeometry(QtCore.QRect(0, 0, 98, 44))
        self.scrollArchiveTourListContents.setObjectName("scrollArchiveTourListContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollArchiveTourListContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.scrollArchiveTourListContents)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.scrollArchiveTourList.setWidget(self.scrollArchiveTourListContents)
        self.verticalLayout_8.addWidget(self.scrollArchiveTourList)
        self.stackedWidget.addWidget(self.pageToursArchive)
        self.pageAbout = QtWidgets.QWidget()
        self.pageAbout.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.pageAbout.setObjectName("pageAbout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageAbout)
        self.verticalLayout_7.setContentsMargins(-1, 30, -1, 220)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelLogo = QtWidgets.QLabel(self.pageAbout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLogo.sizePolicy().hasHeightForWidth())
        self.labelLogo.setSizePolicy(sizePolicy)
        self.labelLogo.setText("")
        self.labelLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogo.setObjectName("labelLogo")
        self.verticalLayout_7.addWidget(self.labelLogo)
        self.label_4 = QtWidgets.QLabel(self.pageAbout)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.pageAbout)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.label_8 = QtWidgets.QLabel(self.pageAbout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.pageAbout)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.pageAbout)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.pageAbout)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.pageAbout)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TravelGuide"))
        self.buttonTours.setText(_translate("MainWindow", "Туры"))
        self.buttonOrders.setText(_translate("MainWindow", "Заказы"))
        self.buttonCustomers.setText(_translate("MainWindow", "Заказчики"))
        self.buttonToursArchive.setText(_translate("MainWindow", "Архив туров"))
        self.buttonAbout.setText(_translate("MainWindow", "О программе"))
        self.label.setText(_translate("MainWindow", "Каталог туров"))
        self.buttonAddTour.setToolTip(_translate("MainWindow", "<html><head/><body><p>Добавить тур</p></body></html>"))
        self.buttonAddTour.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Список заказов"))
        self.label_3.setText(_translate("MainWindow", "Список заказчиков"))
        self.label_5.setText(_translate("MainWindow", "Архив туров"))
        self.label_4.setText(_translate("MainWindow", "TravelGuide"))
        self.label_12.setText(_translate("MainWindow", "Система заказа туров в туристической фирме"))
        self.label_8.setText(_translate("MainWindow", "Версия: 1.0"))
        self.label_9.setText(_translate("MainWindow", "Курсовой проект по предмету \"Объектно-ориентированное программирование\""))
        self.label_11.setText(_translate("MainWindow", "Разработчик: Нестерович Д.В., гр.753501"))
        self.label_10.setText(_translate("MainWindow", "БГУИР - 2019"))

