# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\travelcompany\gui\UpdateTourWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UpdateTourWindow(object):
    def setupUi(self, UpdateTourWindow):
        UpdateTourWindow.setObjectName("UpdateTourWindow")
        UpdateTourWindow.resize(563, 685)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UpdateTourWindow.sizePolicy().hasHeightForWidth())
        UpdateTourWindow.setSizePolicy(sizePolicy)
        UpdateTourWindow.setWindowTitle("")
        UpdateTourWindow.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(248, 248, 248)")
        self.centralwidget = QtWidgets.QWidget(UpdateTourWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dateEnd = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEnd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEnd.setObjectName("dateEnd")
        self.gridLayout.addWidget(self.dateEnd, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.doubleSpinPrice = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinPrice.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinPrice.setMaximum(99999.99)
        self.doubleSpinPrice.setObjectName("doubleSpinPrice")
        self.gridLayout.addWidget(self.doubleSpinPrice, 6, 1, 1, 1)
        self.buttonSave = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSave.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.buttonSave.setObjectName("buttonSave")
        self.gridLayout.addWidget(self.buttonSave, 10, 0, 1, 2)
        self.checkBoxVisa = QtWidgets.QCheckBox(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.checkBoxVisa.setPalette(palette)
        self.checkBoxVisa.setStyleSheet("")
        self.checkBoxVisa.setObjectName("checkBoxVisa")
        self.gridLayout.addWidget(self.checkBoxVisa, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.dateStart = QtWidgets.QDateEdit(self.centralwidget)
        self.dateStart.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateStart.setObjectName("dateStart")
        self.gridLayout.addWidget(self.dateStart, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(7, 0, 7, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textDescription = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textDescription.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textDescription.setObjectName("textDescription")
        self.verticalLayout.addWidget(self.textDescription)
        self.gridLayout.addLayout(self.verticalLayout, 8, 0, 1, 2)
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelName.sizePolicy().hasHeightForWidth())
        self.labelName.setSizePolicy(sizePolicy)
        self.labelName.setStyleSheet("")
        self.labelName.setText("")
        self.labelName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 0, 1, 1, 1)
        self.labelCountry = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCountry.sizePolicy().hasHeightForWidth())
        self.labelCountry.setSizePolicy(sizePolicy)
        self.labelCountry.setText("")
        self.labelCountry.setObjectName("labelCountry")
        self.gridLayout.addWidget(self.labelCountry, 1, 1, 1, 1)
        self.labelDeparture = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDeparture.sizePolicy().hasHeightForWidth())
        self.labelDeparture.setSizePolicy(sizePolicy)
        self.labelDeparture.setText("")
        self.labelDeparture.setObjectName("labelDeparture")
        self.gridLayout.addWidget(self.labelDeparture, 2, 1, 1, 1)
        UpdateTourWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpdateTourWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdateTourWindow)
        UpdateTourWindow.setTabOrder(self.dateStart, self.dateEnd)
        UpdateTourWindow.setTabOrder(self.dateEnd, self.doubleSpinPrice)
        UpdateTourWindow.setTabOrder(self.doubleSpinPrice, self.checkBoxVisa)
        UpdateTourWindow.setTabOrder(self.checkBoxVisa, self.buttonSave)

    def retranslateUi(self, UpdateTourWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("UpdateTourWindow", "Страна:"))
        self.label_8.setText(_translate("UpdateTourWindow", "Цена, USD:"))
        self.buttonSave.setText(_translate("UpdateTourWindow", "Сохранить"))
        self.checkBoxVisa.setText(_translate("UpdateTourWindow", "Виза"))
        self.label_3.setText(_translate("UpdateTourWindow", "Дата выезда:"))
        self.label_7.setText(_translate("UpdateTourWindow", "Место отправления:"))
        self.label_4.setText(_translate("UpdateTourWindow", "Дата приезда:"))
        self.label.setText(_translate("UpdateTourWindow", "Название:"))

